name = "Cy_braindump"
license = "MIT"
licenselink = "https://github.com/chinying/hugo_braindump_theme/blob/master/LICENSE"
description = ""
tags = []
features = []
min_version = "0.41"

[author]
  name = "chinying"
  homepage = ""
